const rowData = [
  {
    floor: 4,
    line: 1,
    unit: "Film Feed",
    model: "FF SV-75",
    performance: "0.8",
    defectRate: "0.1",
  },
  {
    floor: 4,
    line: 3,
    unit: "Metal Heating",
    model: "FF SV-74",
    performance: "0.82",
    defectRate: "0.13",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 4,
    line: 4,
    unit: "Unwinder",
    model: "UW SV-75",
    performance: "0.84",
    defectRate: "0.31",
  },
  {
    floor: 6,
    line: 2,
    unit: "Leveler",
    model: "US SV-75",
    performance: "0.9",
    defectRate: "0.13",
  },
  {
    floor: 6,
    line: 3,
    unit: "Vision",
    model: "FF SV-74",
    performance: "0.4",
    defectRate: "0.11",
  },
  {
    floor: 6,
    line: 5,
    unit: "Film Feed2",
    model: "FF SV-71",
    performance: "0.85",
    defectRate: "0.09",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
  {
    floor: 6,
    line: 8,
    unit: "Metal Heating2",
    model: "FF SV-76",
    performance: "0.73",
    defectRate: "0.01",
  },
];

const colDefs = [
  {
    field: "floor",
    headerName: "층",
    valueFormatter: (p) => `${p.value}F`,
  },
  { field: "line", headerName: "호기" },
  {
    field: "unit",
    headerName: "공정",
    filter: true,
    editable: true,
    cellEditor: "agSelectCellEditor",
    cellEditorParams: {
      values: [
        "Unwinder",
        "Film Feed",
        "Metal Heating",
        "Leveler",
        "Vision",
        "Film Feed2",
        "Metal Heating2",
      ],
    },
  },
  { field: "model", headerName: "모델명", filter: true, floatingFilter: true },
  {
    field: "performance",
    headerName: "가동률",
    valueFormatter: (p) => `${Math.round(Number(p.value) * 100)}%`,
  },
  {
    field: "defectRate",
    headerName: "불량률",
    valueFormatter: (p) => `${Math.round(Number(p.value) * 100)}%`,
  },
];

const nestedData = [
  { country: "Lithuania", litres: 501.9, bottles: 1500 },
  { country: "Czech Republic", litres: 301.9, bottles: 990 },
  { country: "Ireland", litres: 201.1, bottles: 785 },
  { country: "Germany", litres: 165.8, bottles: 255 },
  { country: "Australia", litres: 139.9, bottles: 452 },
  { country: "Austria", litres: 128.3, bottles: 332 },
  { country: "UK", litres: 99, bottles: 150 },
  { country: "Belgium", litres: 60, bottles: 178 },
  { country: "The Netherlands", litres: 50, bottles: 50 },
  { category: "Unwinder", value: 42000, impact: 2.0 },
  { category: "Leveler & EPC", value: 41000, impact: 3.0 },
  { category: "Film Feed", value: 21000, impact: 8.0 },
  { category: "Metal Heating", value: 38000, impact: 5.0 },
  { category: "Film Welding", value: 40000, impact: 4.0 },
  { category: "Vision Inspect", value: 36000, impact: 4.0 },
];

const donutData = [
  { category: "Unwinder", value: 95 },
  { category: "Leveler & EPC", value: 110 },
  { category: "Film Feed", value: 130 },
  { category: "Metal Heating", value: 220 },
  { category: "Film Welding", value: 180 },
  { category: "Vision Inspect", value: 60 },
];

const dummy = { rowData, colDefs, nestedData, donutData };
export default dummy;
